FROM python:3.10-alpine

WORKDIR /opt/apps
COPY apps/controller controller/
COPY apps/grabber  grabber/

WORKDIR /opt/apps/controller
RUN pip install -e .

WORKDIR /opt/apps/grabber
RUN pip install -e .

WORKDIR /opt/apps
ENTRYPOINT ["/usr/local/bin/python3"]